---
- name: install podman
  dnf:
    name:
      - podman
      - cockpit-podman

- name: install pip
  dnf:
    name: python3-pip
    state: present

- name: install podman ansible requirements
  pip:
    name:
      - podman
      - requests
    state: present
